import Head from 'next/head'
import Image from 'next/image';

import Banner from '../components/banner';

import styles from '../styles/Home.module.css'

export default function Home() {
  const handleOnBannerBtnClick = () => {
    console.log('hi , i am banner button');
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Finder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner buttonText="View stores nearby" handleOnClick={handleOnBannerBtnClick} />
      <div className={styles.heroImage}>
        <Image  src="/static/hero-image.png" width={700} height={400} />
      </div>
      </main>
    </div>
  )
}
