import Head from 'next/head'
import Image from 'next/image';

import Banner from '../components/banner';
import Card from '../components/card';

import coffeeStoresData from '../data/coffee-stores.json';

import styles from '../styles/Home.module.css'

export async function getStaticProps(context) {
  return {
    props: {
      coffeeStores: coffeeStoresData,
    },
  }
}

export default function Home(props) {
  const handleOnBannerBtnClick = () => {
    console.log('hi , i am banner button');
  }

  return (
    <div className={styles.container}>
    <Head>
    <title>Coffee Finder</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className={styles.main}>
    <Banner buttonText="View stores nearby" handleOnClick={handleOnBannerBtnClick} />
    <div className={styles.heroImage}>
    <Image  src="/static/hero-image.png" width={600} height={300} />
    </div>

    { props.coffeeStores.length > 0 && (
      <> 
      <h2 className={styles.heading2}>Umar k sary stores</h2>    
      <div className={styles.cardLayout}>     
      {props.coffeeStores.map(coffeeStores => {
        return (
          <Card  
          key={coffeeStores.id}
          name={coffeeStores.name} 
          imgUrl={coffeeStores.imgUrl} 
          href={`/coffee-store/${coffeeStores.id}`} 
          />
          );
      })}
      </div>
      </>
      )}
    </main>
    </div>
    );
}
